apiVersion: v1
kind: Pod
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  containers:
    - name: todo
      image: tejaswirajendra/todo-app:latest
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
